import React from 'react';
// Removed incorrect global CSS import
// import '../../styles/GlowGuide.css'; 

interface GlowGuidePanelProps {
  isOpen: boolean;
  onClose: () => void;
  isOnboarding?: boolean;
  currentOnboardingStep?: number;
}

const GlowGuidePanel: React.FC<GlowGuidePanelProps> = ({ 
  isOpen, 
  onClose, 
  isOnboarding, 
  currentOnboardingStep 
}) => {
  if (!isOpen) return null;

  const renderOnboardingContent = () => {
    switch (currentOnboardingStep) {
      case 1:
        return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 1: Welcome!</h3>
            <p className="text-sm mb-3">We're glad you're here! HeartGlow helps you find the right words for the moments that matter.</p>
            <ul className="list-disc list-inside text-sm space-y-1">
                <li>Click "Let's Get Started!" to move to the next step.</li>
                <li>This GlowGuide panel offers tips for each step.</li>
             </ul>
          </>
        );
      case 2:
         return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 2: Relationship Focus</h3>
            <p className="text-sm mb-3">Thinking about who you want to connect with helps us give better suggestions later.</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>Choose the relationship type that feels most relevant right now.</li>
                <li>Don't worry, you can focus on others later!</li>
                <li>Click "Next" when you've made a selection.</li>
             </ul>
          </>
        );
      case 3:
         return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 3: Craft Your Message</h3>
            <p className="text-sm mb-3">Now, let's draft that first message! Just provide the recipient's name and your main goal.</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>Use the name the AI should use in the message (e.g., "Mom", "Alex").</li>
                <li>Select the core intent (like checking in or saying thanks).</li>
                <li>Click "Draft my Message" to let the AI work its magic!</li>
             </ul>
          </>
        );
      case 4:
        return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 4: Your Draft!</h3>
            <p className="text-sm mb-3">Here's the starting point generated by the AI based on your input.</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>Read it over - does it sound like a good start?</li>
                <li>The placeholder buttons below ("+ Add inside joke") hint at future editing capabilities.</li>
                <li>Click "Continue" if you're happy, or "Try Again" to adjust Step 3.</li>
             </ul>
          </>
        );
      case 5:
        return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 5: Great First Step!</h3>
            <p className="text-sm mb-3">Taking action builds connection. Keep the momentum going!</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>"Add Connection" lets you save this person for easier future messaging (recommended!).</li>
                <li>"Explore What's Next" will continue the tour to introduce HeartSteps guidance.</li>
                <li>Building a daily streak helps grow your GlowScore!</li>
             </ul>
          </>
        );
      case 6:
        return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 6: HeartSteps Guidance</h3>
            <p className="text-sm mb-3">Sometimes you need more than a quick message. HeartSteps helps you navigate complex conversations.</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>Think of it as ongoing support for communication challenges.</li>
                <li>The example shows the type of prompt you might use.</li>
                <li>You can access HeartSteps from your main dashboard later.</li>
             </ul>
          </>
        );
      case 7:
        return (
          <>
            <h3 className="font-semibold text-lg mb-2">💡 Step 7: Ready to Explore!</h3>
            <p className="text-sm mb-3">You've completed the initial onboarding! Choose your next action.</p>
             <ul className="list-disc list-inside text-sm space-y-1">
                <li>Adding connections now makes future messaging easier.</li>
                <li>Exploring the Dashboard shows you your GlowScore, Challenges, and HeartSteps access.</li>
                <li>Crafting another message takes you to the full editor with more options.</li>
                <li>Upgrading helps you track your growth across all features.</li>
             </ul>
          </>
        );
      default:
        return <p className="text-sm text-gray-600 dark:text-gray-400">Loading tips for step {currentOnboardingStep}...</p>;
    }
  };

  const renderGeneralContent = () => {
     // Placeholder for general content when not onboarding
     // TODO: Make this route-aware or provide general help
      return (
          <>
            <h3 className="font-semibold text-lg text-gray-700 dark:text-gray-300 mb-2">General Tips</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
              Need help navigating HeartGlow? Here are some common topics.
            </p>
             <ul className="list-disc list-inside text-sm text-gray-600 dark:text-gray-400 space-y-1">
              <li>How to start a new message from the dashboard.</li>
              <li>Understanding your GlowScore.</li>
              <li>Starting an AI Coaching session.</li>
            </ul>
          </>
      );
  };

  return (
    <div className="glow-guide-panel-overlay" onClick={onClose}>
      <div className="glow-guide-panel-content" onClick={(e) => e.stopPropagation()}>
        <button onClick={onClose} className="glow-guide-close-button" aria-label="Close Glow Guide">×</button>
        <h2 className="text-xl font-semibold mb-4 text-gray-800 dark:text-gray-200 border-b pb-2 border-gray-200 dark:border-gray-700">GlowGuide</h2>
        
        {/* Conditionally render content */}
        <div className="mt-4">
          {isOnboarding ? renderOnboardingContent() : renderGeneralContent()}
        </div>

      </div>
    </div>
  );
};

export default GlowGuidePanel; 