name: Deploy HeartGlow Complete Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: heartglow-dashboard/package-lock.json

      - name: Install dependencies
        run: |
          cd heartglow-dashboard
          npm ci

      # Use a simplified approach with absolute paths
      - name: Prepare deployment workspace
        run: |
          # Store absolute paths
          echo "WORKSPACE_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "DEPLOY_DIR=$(pwd)/deploy" >> $GITHUB_ENV
          
          # Clean and recreate deployment directory
          rm -rf deploy
          mkdir -p deploy
          
          # Create CNAME file in root
          echo "heartglowai.com" > deploy/CNAME
          
          # Create .nojekyll file in root
          touch deploy/.nojekyll
          
          # Debug outputs
          echo "Workspace root: $WORKSPACE_ROOT"
          echo "Deploy directory: $DEPLOY_DIR"
          ls -la deploy

      # Build dashboard for root deployment
      - name: Build dashboard for root
        run: |
          # Navigate to source directory
          cd heartglow-dashboard
          
          # REMOVED: Environment variable for base path (build for root)
          # echo "NEXT_PUBLIC_BASE_PATH=/dashboard" > .env.production.local
          
          # Build the dashboard (for root)
          npm run build
          
          # Copy files using absolute paths to the ROOT deploy directory
          echo "Copying dashboard build files to $DEPLOY_DIR/"
          cp -rv out/* $DEPLOY_DIR/

          # REMOVED: Favicon copy (should be handled by Next.js build output)
          
          # Cleanup
          rm -rf out .next

      # REMOVED STEP: No longer copying the separate root index.html
      # - name: Copy root landing page files 
      #  run: | ... 

      # Display deployment structure
      - name: Show final deployment structure
        run: |
          echo "Final deployment directory structure:"
          ls -la $DEPLOY_DIR
          # Show top-level files/folders in deploy dir
          find $DEPLOY_DIR -maxdepth 1 -ls 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy # Deploy the root directory containing the dashboard build
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
          commit-message: "Deploy dashboard to root" # Updated commit message 