name: Deploy HeartGlow Complete Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: heartglow-dashboard/package-lock.json

      - name: Install dependencies
        run: |
          cd heartglow-dashboard
          npm ci

      # Use a simplified approach with absolute paths
      - name: Prepare deployment workspace
        run: |
          # Store absolute paths
          echo "WORKSPACE_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "DEPLOY_DIR=$(pwd)/deploy" >> $GITHUB_ENV
          
          # Clean and recreate deployment directories
          rm -rf deploy
          mkdir -p deploy/dashboard
          
          # Create CNAME files
          echo "heartglowai.com" > deploy/CNAME
          echo "heartglowai.com" > deploy/dashboard/CNAME
          
          # Create .nojekyll files
          touch deploy/.nojekyll
          touch deploy/dashboard/.nojekyll
          
          # Debug outputs
          echo "Workspace root: $WORKSPACE_ROOT"
          echo "Deploy directory: $DEPLOY_DIR"
          ls -la deploy
          ls -la deploy/dashboard

      # Build dashboard with its enhanced configuration
      - name: Build dashboard
        run: |
          # Navigate to source directory
          cd heartglow-dashboard
          
          # Set environment variables
          echo "NEXT_PUBLIC_BASE_PATH=/dashboard" > .env.production.local
          
          # Build the dashboard
          npm run build
          
          # Copy files using absolute paths
          echo "Copying dashboard files to $DEPLOY_DIR/dashboard/"
          cp -rv out/* $DEPLOY_DIR/dashboard/
          
          # Cleanup
          rm -rf out .next

      # Build login page as the root site
      - name: Build login page for root
        run: |
          # Navigate to source directory
          cd heartglow-dashboard
          
          # Create root config
          cat > next.config.root.js << EOF
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            trailingSlash: true,
            output: 'export',
            images: {
              unoptimized: true,
            }
          }
          module.exports = nextConfig
          EOF
          
          # Back up original config and use root config
          cp next.config.js next.config.js.bak
          cp next.config.root.js next.config.js
          
          # Create root index page from login page
          cp src/pages/login.tsx src/pages/index.tsx
          
          # Build
          npm run build
          
          # Copy files using absolute paths
          echo "Copying root files to $DEPLOY_DIR/"
          cp -rv out/* $DEPLOY_DIR/
          
          # Restore original files
          cp next.config.js.bak next.config.js
          git checkout -- src/pages/index.tsx
          
          # Debug output
          echo "Deploy directory contents after root build:"
          ls -la $DEPLOY_DIR

      # Create redirect files for better navigation
      - name: Create redirect files
        run: |
          # Create redirection file
          cat > $DEPLOY_DIR/dashboard-redirect.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0;url=/dashboard/">
            <title>Redirecting to Dashboard</title>
          </head>
          <body>
            <p>Redirecting to dashboard...</p>
            <script>
              window.location.href = "/dashboard/";
            </script>
          </body>
          </html>
          EOF
          
          # Display deployment structure
          echo "Final deployment directory structure:"
          find $DEPLOY_DIR -type f | head -n 20

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
          commit-message: "Deploy consolidated site with improved path handling" 