name: Deploy HeartGlow Complete Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: heartglow-dashboard/package-lock.json

      - name: Install dependencies
        run: |
          cd heartglow-dashboard
          npm ci

      # Use a simplified approach with absolute paths
      - name: Prepare deployment workspace
        run: |
          # Store absolute paths
          echo "WORKSPACE_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "DEPLOY_DIR=$(pwd)/deploy" >> $GITHUB_ENV
          
          # Clean and recreate deployment directories
          rm -rf deploy
          mkdir -p deploy/dashboard
          
          # Create CNAME files
          echo "heartglowai.com" > deploy/CNAME
          echo "heartglowai.com" > deploy/dashboard/CNAME
          
          # Create .nojekyll files
          touch deploy/.nojekyll
          touch deploy/dashboard/.nojekyll
          
          # Debug outputs
          echo "Workspace root: $WORKSPACE_ROOT"
          echo "Deploy directory: $DEPLOY_DIR"
          ls -la deploy
          ls -la deploy/dashboard

      # Build dashboard with its enhanced configuration
      - name: Build dashboard
        run: |
          # Navigate to source directory
          cd heartglow-dashboard
          
          # Set environment variables
          echo "NEXT_PUBLIC_BASE_PATH=/dashboard" > .env.production.local
          
          # Build the dashboard
          npm run build
          
          # Copy files using absolute paths
          echo "Copying dashboard files to $DEPLOY_DIR/dashboard/"
          cp -rv out/* $DEPLOY_DIR/dashboard/

          # Explicitly copy favicon to the ROOT deploy directory as well
          echo "Copying favicon to $DEPLOY_DIR/"
          cp public/favicon.ico $DEPLOY_DIR/
          
          # Cleanup
          rm -rf out .next

      # Build login page as the root site - REMOVED FOR SIMPLICITY

      # Create redirect files for better navigation
      - name: Create root index.html with meta tags and redirect
        run: |
          # Create root index redirection file with proper meta tags
          cat > $DEPLOY_DIR/index.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <!-- Favicon -->
            <link rel="icon" href="/favicon.ico" />

            <!-- Optimized SEO / Social Sharing Meta Tags -->
            <title>HeartGlow AI: AI Assistant for Thoughtful Communication</title>
            <meta name="description" content="Craft meaningful messages with HeartGlow AI's communication assistant. Connect authentically, navigate tough talks & build stronger relationships." />
            <meta name="keywords" content="AI message generator, communication assistant, emotional intelligence AI, relationship communication, personalized messages, heartfelt messages, thoughtful communication, authentic communication" />
            <meta property="og:title" content="HeartGlow AI: AI Assistant for Thoughtful Communication" />
            <meta property="og:description" content="Craft meaningful messages with HeartGlow AI's communication assistant. Connect authentically, navigate tough talks & build stronger relationships." />
            <meta property="og:image" content="https://heartglowai.com/assets/og-image.png" />
            <meta property="og:url" content="https://heartglowai.com/" />
            <meta property="og:type" content="website" />
            <meta name="twitter:card" content="summary_large_image" />

            <!-- Redirect Logic -->
            <meta http-equiv="refresh" content="0;url=/dashboard/login">
            <script>window.location.replace("/dashboard/login");</script>
          </head>
          <body>
            <p>Redirecting to login... If you are not redirected, <a href="/dashboard/login">click here</a>.</p>
          </body>
          </html>
          EOF

          # Create dashboard-redirect.html (Optional, maybe remove later if not needed)
          # cat > $DEPLOY_DIR/dashboard-redirect.html << EOF ... existing redirect ... EOF
          
          # Display deployment structure
          echo "Final deployment directory structure:"
          find $DEPLOY_DIR -type f | head -n 20

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
          commit-message: "Deploy consolidated site with improved path handling" 