name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install --legacy-peer-deps react@18.3.1 react-dom@18.3.1 react-native-web@0.19.13 @expo/webpack-config firebase expo-router expo-linking

      - name: Create env file
        run: |
          echo "FIREBASE_API_KEY=AIzaSyBZiJPTs7dMccVgFV-YoTejnhy1bZNFEQY" > .env
          echo "FIREBASE_AUTH_DOMAIN=heartglowai.firebaseapp.com" >> .env
          echo "FIREBASE_PROJECT_ID=heartglowai" >> .env
          echo "FIREBASE_STORAGE_BUCKET=heartglowai.firebasestorage.app" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=196565711798" >> .env
          echo "FIREBASE_APP_ID=1:196565711798:web:79e2b0320fd8e74ab0df17" >> .env
          echo "FIREBASE_MEASUREMENT_ID=G-KJMPL1DNPY" >> .env

      - name: Create web-specific index.html
        run: |
          mkdir -p web-build
          cat > web-build/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no"
            />
            <title>HeartGlowAI</title>
            <style>
              html, body, #root {
                width: 100%;
                height: 100%;
                margin: 0;
                padding: 0;
                background-color: #050A14;
              }
              #root {
                display: flex;
                justify-content: center;
              }
              .loading {
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100%;
                color: #fff;
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              }
              .loading img {
                width: 150px;
                height: 150px;
                margin-bottom: 20px;
              }
            </style>
          </head>
          <body>
            <div id="root">
              <div class="loading">
                <img src="heart-logo.png" alt="HeartGlowAI Logo" />
                <h1>Loading HeartGlowAI...</h1>
              </div>
            </div>
            <script src="./App.js"></script>
          </body>
          </html>
          EOL
          cp assets/heart-logo.png web-build/

      - name: Create web entry point
        run: |
          cat > web/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no"
            />
            <title>HeartGlowAI</title>
            <style>
              html, body, #root {
                width: 100%;
                height: 100%;
                margin: 0;
                padding: 0;
                background-color: #050A14;
              }
            </style>
          </head>
          <body>
            <div id="root"></div>
          </body>
          </html>
          EOL

      - name: Build web using Webpack
        run: |
          npx expo export:web || npx webpack

      - name: Create CNAME file
        run: echo "heartglowai.com" > web-build/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: web-build
          token: ${{ secrets.GITHUB_TOKEN }} 