name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Create env file
        run: |
          echo "FIREBASE_API_KEY=AIzaSyBZiJPTs7dMccVgFV-YoTejnhy1bZNFEQY" > .env
          echo "FIREBASE_AUTH_DOMAIN=heartglowai.firebaseapp.com" >> .env
          echo "FIREBASE_PROJECT_ID=heartglowai" >> .env
          echo "FIREBASE_STORAGE_BUCKET=heartglowai.firebasestorage.app" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=196565711798" >> .env
          echo "FIREBASE_APP_ID=1:196565711798:web:79e2b0320fd8e74ab0df17" >> .env
          echo "FIREBASE_MEASUREMENT_ID=G-KJMPL1DNPY" >> .env

      - name: Create web build directory
        run: |
          mkdir -p web-build
          
          # Copy assets
          cp -r assets web-build/
          
          # Create .nojekyll file to prevent GitHub Pages from using Jekyll
          touch web-build/.nojekyll
          
          # Remove any potential README or index.md files that might take precedence
          rm -f web-build/README.md web-build/index.md || true

      - name: Create CNAME file
        run: echo "heartglowai.com" > web-build/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: web-build
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 